apiVersion: v1
kind: Service
metadata:
  name: online-shop-ui-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: online-shop-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
